config/routes.rb
Rails.application.routes.draw do
  get 'searchers/free_search'
  get 'searchers/search'
  root 'searchers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/searchers_controller.rb
class SearchersController < ApplicationController
  QUERY_OPTIONS = %w(title body code user tag stocks created updated)
  INTEGER_QUERY_OPTIONS = %w(stocks created updated)
  def index
  end

  def free_search
    if ! params['free'].empty?
      redirect_to "https://qiita.com/search?q=#{params['free']}"
    else
      redirect_to "https://qiita.com/"
    end
  end

  def search
    if querys_empty?
      redirect_to "https://qiita.com/"
    else
      options = querys.keys
      query_part = options.map{|option| make_part(option)}.compact.join(" ")
      redirect_to "https://qiita.com/search?q=#{query_part}"
    end
  end

  private
  def querys
    params.select{|k, _| QUERY_OPTIONS.include?(k)}
  end

  def querys_empty?
    querys.values.all?(&:empty?)
  end

  def make_part(option)
    return nil if params[option].empty?
    if INTEGER_QUERY_OPTIONS.include?(option)
      "#{option}:" + params["#{option}_inequality"] + params[option]
    else
      params[option].split.map{|q| "#{option}:#{q}"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searchers_helper.rb
module SearchersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QiitaSearcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="jumbotron">
        <h1>Qiita 検索ツール</h1>
      </div>
        <%= yield %>
    </div>
  </body>
</html>

app/views/searchers/index.html.erb
<div class="well">
  <%= form_tag(searchers_free_search_path, method: "get", class: 'input-group') do %>
  <div class="form-group form-group-lg">
    <%= text_field_tag :free, '', class: 'form-control', placeholder: 'search' %>
  </div>
  <div class="input-group-btn">
    <%= submit_tag 'Search', class: 'btn btn-success btn-lg' %>
  </div>
  <% end %>
</div>

<div class="well">
  <%= form_tag(searchers_search_path, method: "get") do %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= label_tag :title %>
      <%= text_field_tag :title, '', class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= label_tag :tag %>
      <%= text_field_tag :tag, '', class: 'form-control' %>
    </div>
  </div>

  <div class="from-row">
    <div class="form-group col-md-6">
      <%= label_tag :user %>
      <%= text_field_tag :user, '', class: 'form-control' %>
    </div>

    <div class="form-group col-md-6">
      <%= label_tag :code %>
      <%= text_field_tag :code, '', class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-4">
      <%= label_tag :stocks %>
      <%= number_field_tag :stocks, nil, min: 0, step: 10 %>
      <%= radio_button_tag :stocks_inequality, '>', true %> upper
      <%= radio_button_tag :stocks_inequality, '<' %> lower
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-4">
      <%= label_tag :created %>
      <%= date_field_tag :created %>
      <%= radio_button_tag :created_inequality, '>', true %> after
      <%= radio_button_tag :created_inequality, '<' %> before
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-4">
      <%= label_tag :updated %>
      <%= date_field_tag :updated %>
      <%= radio_button_tag :updated_inequality, '>', true %> after
      <%= radio_button_tag :updated_inequality, '<' %> before
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-offset-4 col-md-4">
      <%= submit_tag "Search", class:'btn btn-primary btn-block btn-lg' %>
    </div>
    <div class="from-group">
      <%= submit_tag "clear", type: :reset, class: 'btn btn-default btn-lg' %>
    </div>
  </div>

  <% end %>
</div>